FROM centos:7
LABEL Description="This image is used to start the Hedvig Volume plugin for Docker" Vendor="Hedvig" Version="1.0"
RUN yum -y install nfs-utils nfs-utils-lib 
RUN yum -y install yum-plugin-remove-with-leaves
